In [1]:
import numpy as np
import scipy.stats as st
data=[12,15,14,10,18,20,22,25,14,17]
range_=max(data)-min(data)
print(f"range:{range_}")

range:15


In [2]:
variance=np.var(data,ddof=0)
sample=np.var(data,ddof=1)
print(f"population variance:{variance}")

population variance:19.410000000000004


In [3]:
_std=np.std(data,ddof=0)
sample=np.std(data,ddof=1)
print(f"population SD:{_std}")

population SD:4.405678154382138


In [10]:
q1=np.percentile(data,25)
q3=np.percentile(data,75)
iqr=q3-q1
print(f"IQR:{iqr}")

IQR:5.5


In [16]:
import numpy as np
import statistics as st
li=np.random.randint(0,100,10)
print(li)
print("mean:",np.mean(li))
print("median:",np.median(li))
print("mode:",st.mode(li))

[99 62 22 43 60 49 47 98 15 15]
mean: 51.0
median: 48.0
mode: 15


In [21]:
import numpy as np
import statistics as st
u=[99,62,22,43,60,49,47,98,15,15]
std=np.std(u,ddof=0)
sam=np.std(u,ddof=1)
print(f"population SD:{std}")
print(f"sample SD: {sam}")

population SD:28.691462144686877
sample SD: 30.243456592570013


In [1]:
import numpy as np
import statistics as st
u=[99,62,22,43,60,49,47,98,15,15]
print("mean:",np.mean(u))
print("median:",np.median(u))
print("mode:",st.mode(u))

mean: 51.0
median: 48.0
mode: 15


In [4]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [8]:
import numpy as np
arr=np.array(42)
print(arr)

42


In [16]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)
print(arr.ndim)

[1 2 3 4]
1


In [17]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
2


In [15]:
import numpy as np
a=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(a)
print(a.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


In [14]:
a=np.array(42)
print(a.ndim)

0


In [21]:
import numpy as np
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print('number of dimensions:',arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions: 5


In [22]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr[0])

1


In [24]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('2nd element on 1st dim:',arr[0,1])

2nd element on 1st dim: 2


In [26]:
import numpy as np
r=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(r[0,1,2])

6


In [29]:
print(r[1,1,2])

12


In [32]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('last element from 2 nd dim:',arr[-2,-1])

last element from 2 nd dim: 5


In [33]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,])
print(a[1:5])

[2 3 4 5]


In [35]:
import numpy as np
a=np.array([1,2,3,4,5,6,7])
print(a[:4])

[1 2 3 4]


In [41]:
import numpy as np 
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a[:10:3])

[ 1  4  7 10]


In [48]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print(a[6::2])

[ 7  9 11 13 15]


In [53]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a[::])

[1 2 3 4 5]


In [55]:
import numpy as np
a=np.array([2,4,6,8,10])
print(a[0:10:2])

[ 2  6 10]


In [58]:
import numpy as np
a = np.array([1, 2, 3, 4, 5,6,7,8,9,10])
print(a[0:10:1])

[ 1  2  3  4  5  6  7  8  9 10]


In [74]:
import numpy as np
a=np.random.randint(0,50,10)
print(a)
a1=np.array(a)
print(a1[1:50:2])

[ 6 37 17 10 26 12  8 19 42 23]
[37 10 12 19 23]
