In [1]:
import numpy as np
a=np.array([1,2,3,4,5,6])
n=np.array_split(a,3)
print(n[0])
print(n[1])
print(n[2])

[1 2]
[3 4]
[5 6]


In [2]:
import numpy as np
a=np.array([1,2,3,4,5,6])
n=np.array_split(a,3)
print(n[0],n[1])

[1 2] [3 4]


In [5]:
import numpy as np 
a=np.array([[1,2],[3,4],[5,6],[7,8]])
n=np.array_split(a,3)
print(n)

[array([[1, 2],
       [3, 4]]), array([[5, 6]]), array([[7, 8]])]


In [7]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
n=np.array_split(a,5)
print(n)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[7, 8, 9]]), array([[10, 11, 12]]), array([[13, 14, 15]]), array([[16, 17, 18]])]


In [10]:
import numpy as np 
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
n=np.hsplit(a,3)
print(n)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [16]:
import numpy as np
a1=np.array([1,2,3])
a2=np.array([4,5,6])
a=np.dstack((a1,a2))
print(a)

[[[1 4]
  [2 5]
  [3 6]]]


In [13]:
import numpy as np
a1=np.array([1,2,3])
a2=np.array([4,5,6])
a=np.vstack((a1,a2))
print(a)

[[1 2 3]
 [4 5 6]]


In [17]:
import numpy as np
a1=np.array([1,2,3])
a2=np.array([4,5,6])
a=np.hstack((a1,a2))
print(a)

[1 2 3 4 5 6]


In [18]:
import numpy as np
a=np.array([1,2,3,4,5,4,4])
x=np.where (a==4)
print(x)

(array([3, 5, 6]),)


In [19]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8])
x=np.where(a%2==0)
print(x)

(array([1, 3, 5, 7]),)


In [3]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
x=np.where(a%2==1)
print(x)

(array([0, 2, 4, 6, 8]),)


In [6]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10,7,9,10,7,4,5,6,7])
x=np.searchsorted(a,6)
print(x)

5


In [7]:
import numpy as np
a=np.array([6,7,8,9])
x=np.searchsorted(a,7,side='right')
print(x)

2


In [11]:
import numpy as np
a=np.array([1,2,3,5,7,9])
x=np.searchsorted(a,[2.5,4,6])
print(x)

[2 3 4]


In [12]:
import numpy as np
a=np.array([3,2,0,1])
print(np.sort(a))

[0 1 2 3]


In [13]:
import numpy as np
a=np.array(['banana','cherry','apple','dragon fruit'])
print(np.sort(a))

['apple' 'banana' 'cherry' 'dragon fruit']


In [17]:
import numpy as np
a=np.array([True,False,False])
print(np.sort(a))

[False False  True]


In [18]:
import numpy as np
a=np.array([1.5,2.0,1.99,0.001,0.1,1.0,2.04])
print(np.sort(a))

[1.00e-03 1.00e-01 1.00e+00 1.50e+00 1.99e+00 2.00e+00 2.04e+00]


In [24]:
import numpy as np
a=np.array(['1,banana','cherry','apple','dragon fruit'])
print(np.sort(a))

['1,banana' 'apple' 'cherry' 'dragon fruit']


In [30]:
import numpy as np
a=np.array([[3,1,4,5,7,0,2,6],[1,9,1,2,3,8,5,10]])
print(np.sort(a))

[[ 0  1  2  3  4  5  6  7]
 [ 1  1  2  3  5  8  9 10]]


In [34]:
import numpy as np
a=np.array([[3,2,4],[5,0,1]])
print(np.sort(a))

[[2 3 4]
 [0 1 5]]


In [38]:
import numpy as np
a=np.array([[3,2,4,0],['banana',1,'cherry','apple']])
print(np.sort(a))

[['0' '2' '3' '4']
 ['1' 'apple' 'banana' 'cherry']]


In [46]:
import numpy as np
a=np.array([9,0,0.1,5,8,3,7,1,2,4,6])
n=(np.sort(a))
print(n)
print(np.searchsorted(n,3))

[0.  0.1 1.  2.  3.  4.  5.  6.  7.  8.  9. ]
4


In [2]:
import numpy as np
a = np.array([9, 0, 1, 5, 8, 3, 7, 1, 2, 4, 6])
a_sorted = np.sort(a)
print(np.searchsorted(a_sorted, 7))

8


In [22]:
import numpy as n
a=n.array([[3,2,4,0,9],['banana','mango','cherry','apple','cherry']])
print(n.sort(a))

[['0' '2' '3' '4' '9']
 ['apple' 'banana' 'cherry' 'cherry' 'mango']]


In [5]:
import numpy as np
a=np.array([[3,2,4,0,9],['banana','mango','cherry','apple','cherry']])
for x in np.nditer(a,flags=['buffered']):
    print(x)
print(n.sort(a))

3
2
4
0
9
banana
mango
cherry
apple
cherry
[['0' '2' '3' '4' '9']
 ['apple' 'banana' 'cherry' 'cherry' 'mango']]


In [16]:
x='applebananacherrycherrymango'
count=0
k="aeiou"
for i in x:
    if i in k:
        count+=1
print(count)

9


In [29]:
num=8
for i in range(1,11):
    print(f"{num}*{i}={num*i}")

8*1=8
8*2=16
8*3=24
8*4=32
8*5=40
8*6=48
8*7=56
8*8=64
8*9=72
8*10=80


In [33]:
num=8
for i in range(1,11):
    if i%2==0:
        print(f"{num}*{i}={num*i}")

8*2=16
8*4=32
8*6=48
8*8=64
8*10=80


In [40]:
total=0
for i in range(1,101):
    total +=i
print(total)

5050
